// Errors
// ------------------------
const ERROR = "ERROR";

// Conversation
// ------------------------
// CREATE
const CREATE_CONVERSATION = "CREATE_CONVERSATION";
const CONVERSATION_CREATED = "CONVERSATION_CREATED ";
// READ
const READ_CONVERSATION = "READ_CONVERSATION";
// UPDATE
const CONVERSATION_UPDATED = "CONVERSATION_UPDATED";
// DELETE
const DELETE_CONVERSATION = "DELETE_CONVERSATION";
const CONVERSATION_DELETED = "CONVERSATION_DELETED ";
// LIST
const LIST_CONVERSATION = "LIST_CONVERSATION";

// SMS
// ------------------------
const CREATE_NEW_SMS = "CREATE_NEW_SMS";
const NEW_SMS_CREATED = "NEW_SMS_CREATED";
const CREATE_RECIEVED_SMS = "CREATE_RECIEVED_SMS";
const RECIEVED_SMS_CREATED = "RECIEVED_SMS_CREATED";
const UPDATE_SMS_STATUS = "UPDATE_SMS_STATUS";

module.exports = {
  ERROR,
  CREATE_CONVERSATION,
  CONVERSATION_CREATED,
  READ_CONVERSATION,
  CONVERSATION_UPDATED,
  DELETE_CONVERSATION,
  CONVERSATION_DELETED,
  LIST_CONVERSATION,
  CREATE_NEW_SMS,
  NEW_SMS_CREATED,
  CREATE_RECIEVED_SMS,
  RECIEVED_SMS_CREATED,
  UPDATE_SMS_STATUS
};
