const ERROR = "ERROR";
const SMS_SENT = "SMS:SENT";
const SMS_RECIEVED = "SMS:RECIEVED";
const SMS_REQUEST_RECIEVED = "SMS:REQUEST:RECIEVED";
const PROCESSING_COMPLETED = "PROCESSING:COMPLETED";

module.exports = {
  ERROR,
  SMS_SENT,
  SMS_RECIEVED,
  SMS_REQUEST_RECIEVED,
  PROCESSING_COMPLETED
};
