service: conversation-service

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'us-west-2'} # Overwrite the default region used. Default is us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    AWS_ACCOUNT_ID: ${ssm:accountId}
    REGION: ${ssm:region}
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  individually: true
  exclude:
    - node_modules/**
    - src/**
    - .vscode/**
    - dist/**

functions:
  listConversations:
    handler: dist/listConversations.handle
    events:
      - http:
          path: conversation
          method: get
    package:
      include:
        - dist/listConversations.js
  createConversation:
    handler: dist/createConversation.handle
    events:
      - http:
          path: conversation
          method: post
    package:
      include:
        - dist/createConversation.js
  readConversation:
    handler: dist/readConversation.handle
    events:
      - http:
          path: conversation/{recipient}
          method: get
          request:
            parameters:
              paths:
                recipient: true
    package:
      include:
        - dist/readConversation.js
  deleteConversation:
    handler: dist/deleteConversation.handle
    events:
      - http:
          path: conversation/{recipient}
          method: delete
          request:
            parameters:
              paths:
                recipient: true
    package:
      include:
        - dist/deleteConversation.js
  createNewSms:
    handler: dist/createNewSms.handle
    events:
      - http:
          path: conversation/{recipient}/sms
          method: post
          request:
            parameters:
              paths:
                recipient: true
    package:
      include:
        - dist/createNewSms.js
  createRecievedSms:
    handler: dist/createRecievedSms.handle
    events:
      - sns: smsRecieved
    package:
      include:
        - dist/createRecievedSms.js

resources:
  Resources:
    ConversationDynamoTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: recipient
            AttributeType: S
        KeySchema:
          - AttributeName: recipient
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
