service: conversation-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'us-west-2'} # Overwrite the default region used. Default is us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    AWS_ACCOUNT_ID: ${ssm:accountId}
    REGION: ${ssm:region}
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  individually: true

functions:
  listConversations:
    handler: dist/listConversations.handle
    events:
      - http:
          path: conversation
          method: get
  createConversation:
    handler: dist/createConversation.handle
    events:
      - http:
          path: conversation/{phone}
          method: post
          request:
            parameters:
              paths:
                phone: true
  readConversation:
    handler: dist/readConversation.handle
    events:
      - http:
          path: conversation/{phone}
          method: get
          request:
            parameters:
              paths:
                phone: true
  deleteConversation:
    handler: dist/deleteConversation.handle
    events:
      - http:
          path: conversation/{phone}
          method: delete
          request:
            parameters:
              paths:
                phone: true
  createSms:
    handler: dist/createSms.handle
    events:
      - http:
          path: conversation/{phone}/sms
          method: post
          request:
            parameters:
              paths:
                phone: true
  createRecievedSms:
    handler: dist/createRecievedSms.handle
    events:
      - sns: smsRecieved
  updateSmsStatus:
    handler: dist/handlers/updateSmsStatus.handle
    events:
      - sns: smsSent

resources:
  Resources:
    ConversationDynamoTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}